"""Adiciona solicitante_id a Agendamento

Revision ID: 0f1429210246
Revises: 4f21f342919a
Create Date: 2025-06-17 22:52:27.953497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1429210246'
down_revision = '4f21f342919a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitante_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_agendamento_solicitante_id_user'), 'user', ['solicitante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agendamento_solicitante_id_user'), type_='foreignkey')
        batch_op.drop_column('solicitante_id')

    # ### end Alembic commands ###
