"""Criação inicial de todas as tabelas

Revision ID: 4f21f342919a
Revises: 
Create Date: 2025-06-17 22:31:58.583374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f21f342919a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo')),
    sa.UniqueConstraint('nome', name=op.f('uq_grupo_nome'))
    )
    op.create_table('recesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=150), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recesso'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_user_google_id'))
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_bloco', sa.String(length=30), nullable=False),
    sa.Column('laboratorio_id', sa.String(length=50), nullable=False),
    sa.Column('laboratorio_nome', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp_criacao', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_agendamento_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_agendamento_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agendamento'))
    )
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('timestamp_criacao', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_aviso_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aviso'))
    )
    op.create_table('membros_grupo',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_membros_grupo_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_membros_grupo_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'grupo_id', name=op.f('pk_membros_grupo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membros_grupo')
    op.drop_table('aviso')
    op.drop_table('agendamento')
    op.drop_table('user')
    op.drop_table('recesso')
    op.drop_table('grupo')
    # ### end Alembic commands ###
